@extends('layouts.app')

@section('content')
<section id="profil-section">
    <div class="container">
        <h2>ASAL USUL DESA SUKOLILO</h2>
        <div class="space_20px"></div>
        <p>Sejarah Desa Sukolilo tidak terlepas dari sejarah Masyarakat di Kabupaten Malang. Desa ini awalnya dua Desa bernama desa Sukolilo dan Desa Sukodono,Desa Sukolilo berdiri pada hari Sukro Manis / Jum’at Legi tahun Wawu Windu Senggoro atau sekitar tahun 1807 dua abad yang lalu . Alkisah di Dusun Sukolilo terdapat satu keluarga yang tekenal yaitu Mbah Bariman dan Mbah Maimunah beliau adalah sepasang suami istri yang datang dari Mataram ngayokyokarto . Beliau membuka lahan dan bertani kegemaran beliau adalah kesenian andhong / tayub ,gending iling- iling yang terbuat dari emas dan talinya juga dari emas.</p>
        <p>Mbah Bariman dan Mbah Maimunah orang yang dermawan dan berwatak ramah namun yang paling berpengaruh adalah Mbah Maimunah . Mbah Maimunah dengan suka rela memberikan pertolongan kepada sesama yang membutuhkan. Pada suatu ketika ada seorang penguasa yang datang ke gubuk Mbah Maimunah diwaktu itu belum ada kendaraan yang ada hanya kuda dan penusa itu membawa kuda yang mana sepatu / tapel kuda dari penguasa itu rusak / lepas .dengan alat sederhana Mbah maimunah menolong mengganti atau meperbaiki tapel kuda dari penguasa tersebut sehungga penguasa iitu memberi nama dimana Mbah Maimunah tinggal dengan sebutan ”DESA SUKOLILO”  yang artinya suko berarti suka dan lilo berarti Ikhlas atau rela.</p>
        <p>Mbah Maimunah adalah seorang pemimpin di Desa sukolilo yang berani,jujur,tegas dan suka menolong orang lain setelah meninggalnya Mbah mimunah kemudian digantikan oleh keturunanya . Dahulu desa ini terbagi dua yaitu Sukodono dan Sukolilo adapun Sukolilo meliputi pedukuhan Napel dan Pohkecik  Kepala desa Sukolilo yang bernama Aris Semin. Desa Sukodono meliputi satu pedukuhan ( Patuk ) dengan  Kepala desa Sukodono bernama P. Aris Rusbin.berkisar Tahun 1901 s/d 1930.  dengan Kepala desa seumur hidup, Kepala desa Aris Semin dan Kepala Desa Aris Rusbin  adalah Kepala Desa yang dermawan, karena sangat terpengaruh oleh gaya kehidupan masyarakat.</p>
    </div>
</section>

<section id="profil-section">
    <div class="container">
        <h2>SEJARAH PEMBANGUNAN DESA SUKOLILO</h2>
        <div class="space_20px"></div>
        <p>Dilihat dari segi pembangunan yang terjadi di desa Sukolilo  dari tahun ke tahun mengalami banyak peningkatan baik di bidang ekonomi, pembangunan, sosial maupun lingkungan.
        Dahulu desa Sukolilo masih banyak didominasi oleh jalan-jalan tanah yang selalu bermasalah saat  musim hujan. Gedung dan rumah-rumah sederhana, serta fasilitas sangat terbatas. Demikian pula dari segi ekonomi, pendapatan rata-rata masih cukup rendah dengan SDM yang juga pas-pasan.
        Lambat laun melalui kerja keras dari seluruh pihak dan tekad masyarakat desa Sukolilo yang mendambakan perbaikan kualitas hidup, maka saat ini hasil pembangunan di berbagai bidang sudah dapat dirasakan dampak positifnya sama semua lapisan masyarakat Desa.</p>
    </div>
</section>

<section id="profil-section">
    <div class="container">
        <h2>LEGENDA DAN CERITA RAKYAT DESA SUKOLILO</h2>
        <div class="space_20px"></div>
        <h4 class="center-text">ASAL-USUL SUKOLILO</h4>
        <h5 class="center-text">Oleh: Aisyah Dyah Maharani</h5>
        <p>Pada zaman dahulu, jauh sebelum Indonesia merdeka dan penjajah datang menguasai, terdapat sebuah desa dengan beberapa orang yang hidup berdampingan. Keberagaman dan kebersamaan memeluk hangat setiap orang yang berada di desa tersebut. Waktu kian berlalu, masyarakat desa menjalani hidup seperti biasa dan sederhana. Sudah lama desa ini hidup tanpa pemimpin. Biasanya warga desa hanya bergantung pada dua tokoh masyarakat untuk menyelesaikan permasalahan yang ada. Kedua tokoh tersebut adalah Mbok Srinah, yang merupakan sepuh di desa ini, dan Mbah Resi, yang merupakan tokoh agama di desa ini.</p>
        <p>Waktu demi waktu terus berlalu, warga desa masih menjalani hidup dengan sederhana. Pada saat itu, Mbah Resi memiliki dua murid yang sangat setia bernama Sukolimo dan Sukocelo. Keduanya memiliki sifat yang bertolak belakang, namun perbedaan sifat mereka tidak menghentikan mereka untuk tetap setia berguru kepada Mbah Resi. Hingga suatu hari, Mbah Resi mendapat kabar bahwa kesehatan Mbok Srinah semakin menurun. Mbok Srinah pun mengatakan bahwa ia butuh ditemani karena merasa kesepian dengan kondisi kesehatan yang kian menurun. “Aku butuh wong sing iso ngerawat aku. Aku wis raiso urip dewe,” ujar Mbok Srinah. “Sejatine desa iki yo butuh penerus. Umurku wis nyelot tua kanggo dadi pemimpin,” lanjutnya.
        </p>
        <p>Sejak saat itu, Mbah Resi terus terpikirkan akan perkataan Mbok Srinah. Ia pun memanggil kedua murid setianya untuk memberikan sayembara. “Le, aku nduwe sayembara. Awakmu kudu nggolek Kembang Suko. Mengko sing iso nemu bakal tak dadekno pemimpin ing desa iki. Iki Le, tak gawani peta gawe dadi panunjuk dalanmu ben penak,” ucap Mbah Resi dengan tegas. Mendengar hal tersebut, kedua murid setianya langsung kembali ke rumah masing-masing.
</p>
        <p>Sukolimo tumbuh dan besar bersama seorang ibu yang kurang mampu. Ketika ia sampai di rumah, Sukolimo langsung membantu ibunya mempersiapkan kayu bakar yang akan dijual. Sambil membantu ibunya, ia meminta izin untuk mengikuti sayembara dari Mbah Resi. Sukolimo menyampaikan pada ibunya dengan hati-hati dan lembut, “Bu, kulo badhene nyuwun pangestu. Kulo badhe tumut sayembara saking Mbah Resi damel pados Sekar Suko.” Mendengar hal tersebut, sang ibu sangat terkejut dan langsung menghujani seribu pertanyaan untuknya. “Ya Allah, Le, opo gak bahaya? Mengko yen ana apa-apa kepriye? Ibu khuwatir!” ucap sang ibu. “Mboten, Bu. Insya Allah kulo saget njagi diri. Mangke umpami kulo kasil, kulo saget dados pemimpin dateng desa mriki, Bu,” balas Sukolimo dengan sabar. Melihat tekad yang kuat dari Sukolimo, sang ibu pun hanya bisa mendoakan Sukolimo. “Yawis, Le, yen kowe yakin, Ibu ridho. Ibu mesti dongakne kowe, Le. Ati-ati yo, Le,” ujar sang ibu sambil memegang tangan anaknya dengan penuh harap agar anaknya selalu diberi keselamatan.
</p>
        <p>Di sisi lain, Sukocelo yang tumbuh dengan latar belakang keluarga kaya langsung menuju halaman belakang rumah dan meminum arak yang ia simpan secara diam-diam karena teman-temannya sering mengajaknya mabuk-mabukan. Sambil menikmati minumannya, ia berkata, “Alah, alah, wis jelas aku bakal menang. Karek takon pengawalku endi dalan sing paling cepet, banjur mengko karek menehi duwit ben mingkem, hahahahah.” Ia memang sering menghambur-hamburkan uangnya untuk memenuhi keinginan dan kebutuhannya. Setelah puas dengan araknya, Sukocelo berangkat dengan bekal peta yang sudah ia tandai, mana jalan yang tercepat hasil bertanya pada pengawalnya. Ia juga membawa beberapa arak untuk bekalnya di jalan. Di sisi lain, Sukolimo pun berangkat dengan langkah penuh pasti serta diiringi doa dari ibunya, ditambah dengan bekal sedikit makanan dan minuman yang disiapkan oleh ibunya. Dalam perjalanannya, mereka mengambil rute perjalanan yang berbeda. Sukolimo berangkat dari arah timur sedangkan Sukocelo berangkat dari arah barat.
</p>
        <p>Sukolimo pun berjalan sambil bersenandung dan melihat sekitar. Tak lama, ia pun sampai di sebuah daerah yang disambut dengan sebuah pathuk (alat batas) yang ukurannya cukup besar. Setelah menyadari akan pathuk tersebut, ia terus melakukan perjalanan hingga ia berhenti karena melihat ada seorang kakek tua yang tampak kelelahan. Kakek tua itu berhenti di pinggir jalan dan duduk di samping gerobaknya yang mengangkut banyak sekali pathuk. Dengan rasa iba, Sukolimo berjalan mendekat ke tempat kakek tua itu berada. “Mbah, panjenengan sampun dhahar?” tanyanya sambil memegang pundak sang kakek. “Durung, Le,” jawab kakek tua itu lirih. Mendengar hal tersebut, ia pun langsung mengambil bekal makanan dan minuman yang dibawakan oleh ibunya, lalu memberikannya kepada kakek tua itu. Sang kakek pun tidak henti-hentinya berterima kasih dan berkata, “Suwun yo, Le, kowe wong sing apik. Aku percoyo kowe bakal mulya.” Sukolimo pun tersenyum dan melanjutkan perjalanannya.
</p>
        <p>Di jalan yang berbeda, Sukocelo telah sampai di sebuah daerah. Daerah tersebut sepanjang jalannya banyak poh (buah mangga) dan kecik (biji buah sawo). Karena perjalanan yang cukup jauh, ia pun kelelahan dan memutuskan untuk beristirahat sejenak. Ia membuka satu botol arak yang dibawanya dan meneguknya dengan nikmat. Tanpa terasa, ia telah menghabiskan satu botol arak hingga membuatnya sedikit mabuk. Akhirnya, ia memutuskan untuk melanjutkan perjalanannya. Dari kejauhan, ia melihat seorang perempuan paruh baya yang sedang memikul dua keranjang berisikan poh dan kecik. Sukocelo yang berniat untuk membantu perempuan tersebut pun berjalan mendekat. Ia menawarkan bantuan untuk membawa keranjang tersebut, namun karena kondisi Sukocelo sudah mabuk, ia tidak bisa menjaga keseimbangannya. Ia pun terjatuh dan isi dari keranjang tersebut ikut jatuh berserakan. Sukocelo dengan sigap memasukkan buah yang berjatuhan itu ke dalam keranjang. Namun tentu banyak buah yang sudah rusak dan tidak bisa dimakan lagi. Ia pun langsung berinisiatif mengeluarkan beberapa lembar uang dengan maksud untuk mengganti kerugian yang telah ia perbuat. Perempuan paruh baya itu pun marah dan berkata, “Kowe iki bocah apik, tapi seneng ngombe lan ngumbar bandha. Dadine malah gak ngewangi blas! Sing eleng, le, gak kabeh iso mbok ganti nganggo duwit!” Mendengar perkataan itu, Sukocelo pun tidak dapat menahan emosinya dan langsung berlari meninggalkan daerah tersebut. Ia marah tetapi juga sedih.
</p>
        <p>Sukocelo pun tiba di sebuah daerah yang di sepanjang jalannya ditemukan sepatu kuda. Ia yang masih penuh dengan emosi pun menendang sepatu kuda ke sana kemari. Dari kejauhan, Sukolimo memantau perilaku Sukocelo. Perilaku Sukocelo semakin parah hingga sepatu kuda yang ia tendang merusak benda-benda yang ada di sekitarnya. Sukolimo pun menghampirinya dan berusaha mencegah Sukocelo. Namun karena masih penuh dengan emosi dan di bawah pengaruh arak, Sukocelo justru memukul Sukolimo hingga terjadi pertengkaran. Sukocelo terus-menerus melayangkan tinjuan kepada Sukolimo. Sebagai bentuk perlindungan diri, Sukolimo pun menangkis tinjuan tersebut. Tidak hanya tinjuan, Sukocelo juga menendang Sukolimo yang langsung ditangkis oleh Sukolimo. Pertengkaran tersebut terjadi sekitar 15-20 menit. Sukolimo sesekali juga ikut melayangkan tinjuan dan tendangan kepada Sukocelo. Hingga tiba waktunya saat Sukolimo kehabisan tenaga dan hampir pingsan. Sukolimo terjatuh dan tidak mampu untuk bangkit kembali. Melihat hal itu, Sukocelo yang sudah mulai sadar pun menghentikan serangannya dan mengulurkan tangan untuk membantu Sukolimo. Sukolimo pun menerima bantuan itu dan akhirnya menepi untuk duduk di bawah pohon dengan bantuan dari Sukocelo.
</p>
        <p>Beberapa saat kemudian, datanglah Mbah Resi dan segera menghampiri mereka. “Walah, walah, mesti awakmu podo iki mari tukaran,” ujar Mbah Resi dengan lantang. “Ojo tukaran! Pancene awakmu wis nemu opo sing kudu kok goleki?” lanjutnya. Mendengar pertanyaan itu, kedua pemuda itu pun menggeleng. Mbah Resi pun tersenyum sambil menggeleng dan berkata, “Kembang Suko iku sejatine ora ana. Lelungan iki ana kanggo awakmu supaya awakmu iso ngenali jati dirimu dewe. Apa sing kok goleki asline ana ing njero awakmu dewe, Le.” Kedua pemuda pun termenung dan terus fokus mendengarkan ucapan Mbah Resi. Mbah Resi memegang pundak kedua pemuda tersebut sambil memejamkan mata. Ia melihat kejadian beberapa waktu kebelakang perjalanan mereka hari ini. “Awakmu maeng ngewenehi panganan wong tua to, Le?” Tanya Mbah Resi kepada Sukolimo. “Kuwi artine awakmu bocah sing lilo lan andhap asor,” lanjutnya. Mbah Resi menoleh ke arah Sukocelo dan bertanya, “Awakmu maeng ngewangi ibu-ibu to, Le? Nanging podo ceblok mergo awakmu ngombe.” Mendengar itu, Sukocelo hanya bisa mengangguk lemah dan sedih. Mbah Resi memegang pundak Sukocelo dan berkata, “Asline atimu becik nanging lingkunganmu sing bendinane ngombe rakaruan iku sing ngerusak awakmu dewe.”
</p>
        <p>“Yawis saiki ayo podo melu aku,” ucap Mbah Resi. Mereka bertiga pun berjalan menuju sebuah rumah kecil tempat kediaman Mbok Srinah. “Niki lare-lare ingkang saget ngerawat lan dados peneruse panjenengan,” ujar Mbah Resi kepada Mbok Srinah. Mbok Srinah pun tersenyum dan melebarkan kedua tangannya sambil berkata, “Reneo, Le.” Kedua pemuda itu pun mendekat dan Mbok Srinah memegang tengkuk kedua pemuda itu. Mbok Srinah terkejut, “Le, awakmu iki asline seduluran,” ujarnya tak menyangka. “Awakmu nduwe toh sing podo,” lanjutnya. Ternyata, Sukolimo dan Sukocelo adalah anak kandung Mbok Srinah. “Awakmu bien diemong karo ibumu sing saiki, mergo aku kudu ngurus desa iki ing masa susah. Ngapuranen ibumu iki yo, Le.” Mbok Srinah menjelaskan kejadian beberapa tahun lalu. Kedua pemuda itu pun terkejut dan langsung sujud ke kaki Mbok Srinah. Mereka berdua meyakini prinsip yang sama bahwa surga ada di bawah telapak kaki ibu maka bagaimanapun keadaannya mereka harus terus menghormati dan menyayangi ibu.
</p>
        <p>Akhirnya, Sukolimo dan Sukocelo pun bersama-sama merawat Mbok Srinah. Sayangnya, keadaan Mbok Srinah tidak kian membaik. Hingga akhirnya, Mbok Srinah memberikan wasiat kepada kedua anaknya, “Le, awakmu kudu nerusne penggaweanku kanggo mimpin desa iki. Dadekno lelungan sing tau kok lakoni kanggo sangu ben desa iki maju. Aku titip desa iki yo, Le.” Setelah wasiat itu diberikan, keesokan harinya diketahui bahwa Mbok Srinah telah wafat.
</p>
        <p>Setelah Mbok Srinah wafat, Mbah Resi menobatkan Sukolimo sebagai kepala desa untuk memimpin desa ini. Hal ini dilakukannya karena ia mengetahui apa saja yang dilakukan kedua pemuda itu saat sayembara. Ketulusan yang dimiliki seorang Sukolimo membuat Mbah Resi yakin bahwa Sukolimo lah yang pantas menjadi pemimpin. Namun, Sukolimo menolak hal tersebut. Ia ingin jabatan pemimpin itu diberikan kepada Sukocelo karena ia yakin bahwa Sukocelo sebenarnya memiliki hati yang baik, suka menolong, dan lebih kuat. Sukolimo pun berkata pada Mbah Resi, “Mbah, kula ngeraos Sukocelo langkung pantes damel mimpin desa niki. Sejatinipun larene niku sae lan remen tulung tinulung. Lare niku purun ngandapaken pangroso damel mbiantu kula menawi kula gerah. Sukocelo niku nggih langkung kiat tinimbang kula, mbah.” Mendengar hal itu, Sukocelo pun menggeleng dan berkata, “Mboten, mbah, kula mboten langkung sae tinimbang Sukolimo. Kula tasik kasusahan damel nahan pangroso kula kiambak.” Dengan ikhlas, Sukocelo memberikan jabatan itu kepada Sukolimo. Mbah Resi yang melihat ketulusan dan kebijaksanaan Sukolimo serta keikhlasan dan kekuatan yang dimiliki oleh Sukocelo pun menjadikan Sukolimo sebagai pemimpin dan Sukocelo sebagai panglima yang membantu Sukolimo memimpin desa ini. Sukolimo pun memimpin desa ini dengan dibantu Sukocelo sebagai panglimanya. Awalnya, mereka membagi wilayah kekuasaan pimpinan mereka menjadi dua bagian yaitu Desa Sukolilo dan Desa Sukodono. 
</p>
        <p>Seiring berjalannya waktu, ketika Indonesia mulai memiliki pemerintahan yang terstruktur mereka mendapat amanah dari pemerintahan untuk menggabungkan kedua desa tersebut menjadi sebuah kesatuan Desa Sukolilo yang artinya senang ikhlas. Suko yang artinya senang dan lilo yang artinya ikhlas merupakan sebuah doa untuk desa ini agar menjadi desa yang penuh dengan kebahagiaan dan keikhlasan. Mereka berharap seluruh warga di desa ini bisa ikhlas untuk saling memberi, saling menolong, dan rukun hidup bersama. Mereka memberi nama untuk setiap daerah yang ada di desa ini dengan pengalaman perjalanan mereka. Daerah yang terlihat terdapat pathuk besar di bagian depan adalah Dusun Pathuk, daerah yang memiliki banyak poh (buah mangga) dan kecik (biji buah sawo) adalah Dusun Pohkecik, dan daerah yang memiliki banyak sepatu kuda adalah Dusun Napel. 
</p>
        <p>Sukocelo dan Sukolimo saling membantu dalam memimpin Desa Sukolilo, ditambah dengan Sukocelo yang sudah tidak lagi mabuk-mabukan dan Sukolimo menjadi semakin bijak. Warga di desa ini pun hidup rukun berdampingan. Kekayaan sumber daya alam juga dikelola dengan baik. Kehidupan Desa Sukolilo pun lebih berwarna dan menyenangkan.
</p>
        
    </div>
</section>

@endsection
